### ISSUE TITLE
Invalid Slot error when using Alveary with Breedertron.

### ISSUE THREAD

**Issue by MrWisski** [FrostyFire1/GTNH_OC_SCRIPTS#3] opened 2024-12-09 20:21 UTC
This is the error. It runs, starting with a completely empty Alveary, inserts a queen and a drone, then gets stuck with bees inside the Alveary output hex. It does this even with a completely fresh install.

![breedertronERROR](https://github.com/user-attachments/assets/9e9779eb-2909-461c-a2e4-12c245e4e35b)

This is the inside of the Alveary, after the error has occured.

![breederAlveary](https://github.com/user-attachments/assets/d6224a74-842d-41d8-9b9e-ed00e974c6e1)

This is the current setup of the Alveary : 

1 Mutator : 45 Eyes of Ender
4x Stimulators, each with 4x -19% lifespan tubes.
Enough Hygroregulators to make it Normal/Normal.
1x Hatchery
1x Lighting
1x Rain Shield

![breederSETUP](https://github.com/user-attachments/assets/81c3e901-ee59-48b5-b942-00d8992e8664)

Left diamond is Storage.
Top diamond is Trash
Right Gold is output
Bottom is LuV Scanner (Elite Scanner), with honey on permanent export into tank.

The transposer is against a plain Alveary block at the bottom, and seems to be able to access the alveary.

**Comment by FrostyFire1** [comment] 2024-12-11 13:54
Issue caused by loop in cycleIsDone ending one slot too late. fixed in 8c66595, please run setup.lua to update the program and let me know if that fixed it

**Comment by MrWisski** [comment] 2024-12-13 16:25
Things seem to be running now. There are a few warnings issued, but the first one was my fault (full garbage), and the others didn't seem to mean anyhting?

![BreederWORKING](https://github.com/user-attachments/assets/bf424264-99b3-4e55-9b90-3d47c4bf2562)

The next page show more warnings - the scanner output chest is completely empty when checked, and all bees in the garbage chest are scanned. No chest is full, and the scanner is empty as well.

![BreederWORKINGMore](https://github.com/user-attachments/assets/8ebc4623-0025-49b0-aafd-bf2656d4ca5b)

**Comment by FrostyFire1** [comment] 2024-12-14 11:56
Given your setup this is to be expected. The scanner only has one slot and the program tries to shove every bee in there immediately. If you replace your scanner with a chest that extracts the bees into the scanner these warnings should disappear.

**Closed as completed by FrostyFire1** 2024-12-14 11:56 UTC
